// apps/frontend/web/chamaai-ui/src/app/shared/components/radio-card/radio-card.component.ts
import type { ClassValue } from 'clsx';

import {
  ChangeDetectionStrategy,
  Component,
  computed,
  input,
  output,
  ViewEncapsulation,
} from '@angular/core';
import { CommonModule } from '@angular/common';

import { mergeClasses } from '@shared/utils/merge-classes';
import {
  radioCardGroupVariants,
  radioRowVariants,
  radioBulletVariants,
  badgeVariants,
} from './radio-card.variants';

export interface SimpleRadioCardOption<T extends string = string> {
  value: T;
  label: string;
  description?: string;
  badge?: string;
}

@Component({
  selector: 'z-radio-card-group',
  exportAs: 'zRadioCardGroup',
  standalone: true,
  imports: [CommonModule],
  changeDetection: ChangeDetectionStrategy.OnPush,
  encapsulation: ViewEncapsulation.None,
  template: `
    <div
      role="radiogroup"
      [attr.aria-disabled]="disabled() || undefined"
      [class]="groupClasses()"
    >
      @for (option of options(); track option.value; let i = $index) {
      <button
        type="button"
        role="radio"
        [attr.aria-checked]="option.value === value()"
        [attr.aria-label]="option.label"
        [attr.name]="name()"
        (click)="onSelect(option.value)"
        [class]="getRowClasses(i > 0, option.value === value())"
        [attr.data-state]="option.value === value() ? 'checked' : 'unchecked'"
      >
        <!-- Radio Bullet -->
        <span
          aria-hidden="true"
          [class]="getBulletClasses(option.value === value())"
        >
          @if (option.value === value()) {
          <svg
            class="h-3 w-3 text-primary-foreground"
            viewBox="0 0 24 24"
            fill="none"
            stroke="currentColor"
            stroke-width="3"
            stroke-linecap="round"
            stroke-linejoin="round"
          >
            <polyline points="20,6 9,17 4,12"></polyline>
          </svg>
          }
        </span>

        <!-- Text & Badge -->
        <span class="flex flex-1 items-center justify-between gap-2">
          <span class="font-light leading-none">{{ option.label }}</span>
          @if (option.badge) {
          <span [class]="getBadgeClasses(option.badge)">
            {{ option.badge }}
          </span>
          }
        </span>
      </button>
      }
    </div>
  `,
})
export class ZardRadioCardGroupComponent<T extends string = string> {
  readonly options = input.required<SimpleRadioCardOption<T>[]>();
  readonly value = input<T | null>(null);
  readonly name = input<string>();
  readonly disabled = input<boolean>(false);
  readonly class = input<ClassValue>('');

  readonly valueChange = output<T>();

  protected readonly groupClasses = computed(() =>
    mergeClasses(
      radioCardGroupVariants(),
      this.disabled() && 'opacity-60 pointer-events-none',
      this.class()
    )
  );

  protected getRowClasses(showDivider: boolean, checked: boolean): string {
    return mergeClasses(
      radioRowVariants({
        showDivider,
        checked,
        disabled: this.disabled(),
      })
    );
  }

  protected getBulletClasses(checked: boolean): string {
    return mergeClasses(radioBulletVariants({ checked }));
  }

  protected getBadgeClasses(badge: string): string {
    const variant =
      badge.toLowerCase() === 'profissional' ? 'profissional' : 'default';
    return mergeClasses(badgeVariants({ variant }));
  }

  protected onSelect(selectedValue: T): void {
    if (!this.disabled()) {
      this.valueChange.emit(selectedValue);
    }
  }
}

// Single radio card component (individual variant)
@Component({
  selector: 'z-radio-card',
  exportAs: 'zRadioCard',
  standalone: true,
  imports: [ZardRadioCardGroupComponent],
  changeDetection: ChangeDetectionStrategy.OnPush,
  encapsulation: ViewEncapsulation.None,
  template: `
    <z-radio-card-group
      [options]="[{ value: value(), label: label(), badge: badge() }]"
      [value]="checked() ? value() : null"
      [name]="name()"
      [disabled]="disabled()"
      [class]="class()"
      (valueChange)="onSelect($event)"
    />
  `,
})
export class ZardRadioCardComponent<T extends string = string> {
  readonly value = input.required<T>();
  readonly label = input.required<string>();
  readonly badge = input<string>();
  readonly checked = input<boolean>(false);
  readonly name = input<string>();
  readonly disabled = input<boolean>(false);
  readonly class = input<ClassValue>('');

  readonly valueChange = output<T>();

  protected onSelect(selectedValue: T): void {
    this.valueChange.emit(selectedValue);
  }
}

// apps/frontend/web/frontend/src/components/ui/radio-card.tsx
'use client';

import * as React from 'react';
import { cn } from '@/lib/utils';
import { Check } from 'lucide-react';

export interface SimpleRadioCardOption<T extends string = string> {
  value: T;
  label: string;
  description?: string;
  badge?: string;
}

export interface RadioCardGroupProps<T extends string = string> {
  options: SimpleRadioCardOption<T>[];
  value: T | null;
  onChange: (value: T) => void;
  className?: string;
  name?: string;
  disabled?: boolean;
}

// Container representing the whole card group (single bordered box with stacked rows)
export function RadioCardGroup<T extends string = string>({
  options,
  value,
  onChange,
  className,
  name,
  disabled,
}: RadioCardGroupProps<T>) {
  return (
    <div
      role="radiogroup"
      aria-disabled={disabled || undefined}
      className={cn(
        'rounded-md border bg-background overflow-hidden text-sm',
        disabled && 'opacity-60 pointer-events-none',
        className
      )}
    >
      {options.map((opt, i) => (
        <RadioRow<T>
          key={opt.value}
          showDivider={i !== 0}
          option={opt}
          checked={opt.value === value}
          onSelect={onChange}
          name={name}
        />
      ))}
    </div>
  );
}

interface RadioRowProps<T extends string> {
  option: SimpleRadioCardOption<T>;
  checked: boolean;
  onSelect: (value: T) => void;
  name?: string;
  showDivider: boolean;
}

function RadioRow<T extends string>({
  option,
  checked,
  onSelect,
  name,
  showDivider,
}: RadioRowProps<T>) {
  return (
    <button
      type="button"
      role="radio"
      aria-checked={checked}
      aria-label={option.label}
      name={name}
      onClick={() => onSelect(option.value)}
      className={cn(
        'flex w-full items-center gap-2 px-4 py-3 outline-none text-left transition-colors',
        'focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 focus-visible:z-10',
        'hover:bg-accent/50 cursor-pointer',
        // checked && 'bg-accent/20',
        showDivider && 'border-t border-border'
      )}
      data-state={checked ? 'checked' : 'unchecked'}
    >
      {/* Bullet */}
      <span
        aria-hidden
        className={cn(
          'grid place-items-center rounded-full border mt-0.5 h-4 w-4 shrink-0',
          checked ? 'border-blue-600 bg-blue-600' : 'border-muted-foreground'
        )}
      >
        {checked && (
          <Check className="h-3 w-3 text-primary-foreground" strokeWidth={3} />
        )}
      </span>
      {/* Text & badge */}
      <span className="flex flex-1 items-center justify-between gap-2">
        <span className="font-light leading-none">{option.label}</span>
        {option.badge && (
          <span
            className={cn(
              'rounded-md border px-2 py-0.5 text-[10px] font-medium uppercase tracking-wide',
              option.badge.toLowerCase() === 'profissional'
                ? 'bg-primary text-primary-foreground border-primary'
                : 'text-muted-foreground'
            )}
          >
            {option.badge}
          </span>
        )}
      </span>
    </button>
  );
}

// Single item variant if someone wants just one (not used in screenshot but handy)
export interface RadioCardProps<T extends string = string>
  extends Omit<SimpleRadioCardOption<T>, 'badge'> {
  badge?: string;
  checked: boolean;
  onSelect: (value: T) => void;
  className?: string;
}

export function RadioCard<T extends string = string>({
  value,
  label,
  badge,
  checked,
  onSelect,
  className,
}: RadioCardProps<T>) {
  return (
    <RadioCardGroup
      options={[{ value, label, badge }]}
      value={checked ? value : null}
      onChange={onSelect}
      className={className}
    />
  );
}

export default RadioCardGroup;
